project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*.ipynb"
  resources:
    - "*.ipynb"

website:
  title: "Numerical Analysis"
  favicon: "logo_calcul_scientifique_transparent.png"
  navbar:
    collapse-below: xl
    logo: "logo_calcul_scientifique_transparent.png"
    logo-alt: "Course logo"
    left:
      - href: notes.qmd
        text: Lecture Notes
        icon: book
      - href: slides.qmd
        text: Slides
        icon: easel
      - href: notebooks.qmd
        text: Notebooks
        icon: code-slash
      - href: quizzes.qmd
        text: Quizzes
        icon: patch-question
      - href: archives.qmd
        text: Archives
        icon: archive
      - href: links.qmd
        text: Useful Links
        icon: link-45deg
      - href: credits.qmd
        text: Credits
        icon: people
    right:
      - href: https://www.nyu.edu/paris
        text: '<img src="nyu_paris_logo_color.png" alt="NYU Paris" class="navbar-nyu-logo">'

editor:
    render-on-save: true

format:
  html:
    theme:
      light: default
      dark: slate
    css: styles.css
    toc: true
