project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*.ipynb"
  resources:
    - "*.ipynb"

website:
  title: "Numerical Analysis"
  navbar:
    left:
      - href: notes.qmd
        text: Lecture Notes
      - href: slides.qmd
        text: Slides
      - href: notebooks.qmd
        text: Notebooks
      - href: quizzes.qmd
        text: Quizzes
      - href: links.qmd
        text: Useful Links
      - href: credits.qmd
        text: Credits

editor:
    render-on-save: true

format:
  html:
    theme:
      light: default
      dark: darkly
    css: styles.css
    toc: true
